### ISSUE TITLE
PHP:  Root package 'bandwidth/sdk' cannot require itself in its composer.json

### ISSUE THREAD

**Issue by rsarceno** [Bandwidth/php-sdk#11]
When I try to install  "composer require bandwidth/sdk"

I'm getting the following
Using version ^2.13 for bandwidth/sdk
Root package 'bandwidth/sdk' cannot require itself in its composer.json

Composer version 1.10.13

>>> composer.json
{
  "name": "bandwidth/sdk",
  "type": "library",
  "description": "Bandwidth's set of APIs",
  "keywords": [
    "bandwidth",
    "API",
    "SDK"
  ],
  "homepage": "https://github.com/bandwidth/php-sdk",
  "license": "MIT",
  "authors": [
    {
      "name": "APIMatic SDK Generator",
      "email": "support@apimatic.io",
      "homepage": "https://apimatic.io",
      "role": "API Tool"
    }
  ],
  "require": {
    "ext-SimpleXML": "*",
    "php": ">=5.4.0",
    "ext-curl": "*",
    "ext-json": "*",
    "ext-mbstring": "*",
    "mashape/unirest-php": "~3.0.1",
    "apimatic/jsonmapper": "~1.3.0"
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "^2.7",
    "phan/phan": "^1.2"
  },  
  "autoload": {
    "psr-4": {
      "BandwidthLib\\": "src/"
    }
  },
}

Appreciate any info

**Comment by jmulford-bw** [comment]
Hi @rsarceno,

I was unable to replicate this on a fresh PHP environment. Can you send over the entire composer.json file that you're using for your project? I'm wondering if you have a name conflict with this package, since that seems to be a cause for this issue

**Comment by hamermike** [comment]
Hey @rsarceno - We're closing this issue due to lack of updates, please feel free to update again if needed.
