### ISSUE TITLE
Undefined properties in createMessage response

### ISSUE THREAD

**Issue by jwpoole** [Bandwidth/php-sdk#9]
We just went live with v2 and we're seeing an undefined property error when trying to access the response object that's generated when creating an SMS message.

The code is taken straight from the [PHP “Send Text Message” example here](https://dev.bandwidth.com/sdks/php.html) but adjusted to try and access data from the `$response` variable.

Here's the error:
```
Undefined property: BandwidthLib\\Http\\ApiResponse::$id
```

Here's a dump of the object returned by the call to `createMessage()`:
```
[result:BandwidthLib\Http\ApiResponse:private] => BandwidthLib\Messaging\Models\BandwidthMessage Object
    (
        [id] => 1234567890123abc45abcdefgh67i
        [owner] => +11234567890
        [applicationId] => 123456a7-8901-2bcd-e345-f6g789h0i12j
        [time] => 2020-03-05T19:27:21.534Z
        [segmentCount] => 1
        [direction] => out
        [to] => Array
            (
                [0] => +11234567890
            )

        [from] => +11234567890
        [media] => 
        [text] => Test Message
        [tag] => 
    )
```

As you can see, it appears that all of the data returned is contained within private object properties. This makes it so that we cannot determine what the ID or other attributes of the successfully sent message are.

Please advise.

**Comment by jmulford-bw** [comment]
Hey @jwpoole,

Are you getting the response object field like this?

```
$response->getResult()->id
```

I don't think those docs you linked are clear in expressing this (other parts of the docsite are more expressive in this). If that's the case and this works for you, let us know and we'll update the sdk page as well to reflect this

**Comment by jwpoole** [comment]
@jmulford-bw, sorry for the delay. I must have missed the notification from github that you had replied here, and then it just got lost in the shuffle with the whole covid fiasco. 

`getResult()->id` works perfectly, thanks for that. 

It looks like the examples in the docs reflect this. Not sure if they were always that way and I just missed it, or if they've been updated since this issue was created. Either way, thanks for the continued support. This one's good to go on my end.

**Comment by jmulford-bw** [comment]
@jwpoole Awesome glad it's all good, I'll close out this issue. Also we did update the docs in the mean time (they weren't clear on this)
